baseurl = "https://tangraplay.petrovs.info"

languageCode = "bg-bg"

Title = "TangraPlay"

# Copyright notice. This is displayer in the footer.

copyright = "&copy; 2020 Blagovest Petrov"

theme = "potato-dark"



[params]

  paginate = 10

  # Social accounts. Link to these accounts are displayed in the header and

  # footer

  # twitter = "Your Twitter username"

  # facebook = "Your Facebook username"

  # instagram = "Your Instagram username"

  # github = "Your GitHub username"

  gitlab = "https://code.petrovs.info"

  # npm = "Your npm username"

  # codepen = "Your CodePen username"

  # dribbble = "Your Dribbble username"

  # fivehundredpx = "Your 500px username" # 500px

  # flickr = "Your Flickr username"

  # pinterest = "Your Pinterest username"

  # tumblr = "Your Tumblr username"

  # vimeo = "Your Vimeo username"

  # youtube = "Your YouTube username"

  # linkedin = "Your LinkedIn username"

  # Disqus shortname

  # disqus = ""

  # Google Analytics API key.

  # ga_api_key = "Your Google Analytics tracking id"

  # Logo image. This is displayed ogp image.

  # logo = "/path/to/logo"

  # favicon = "/path/to/favicon"



[[menu.main]]

    name = "Начало"

    url = "/"

    weight = 1



[[menu.main]]

    name = "Снимки"

    url = "/screenshots"

    weight = 2



[[menu.main]]

    name = "Сваляне"

    url = "/downloads"

    weight = 3



[related]

  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.

  threshold = 80



  # To get stable "See also" sections we, by default, exclude newer related pages.

  includeNewer = false



  # Will lower case keywords in both queries and in the indexes.

  toLower = false



  [[related.indices]]

  name = "keywords"

  weight = 150

  [[related.indices]]

  name  = "author"

  toLower = true

  weight = 30

  [[related.indices]]

  name  = "tags"

  weight = 100

  [[related.indices]]

  name  = "date"

  weight = 10

  pattern = "2017"
